server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: doyoung.c3yf6hovsgph.ap-northeast-2.rds.amazonaws.com:3306/sugang
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-location:
    - /mappers/*.xml